---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook: AgDX2pFJwfwZmw/qIiTr5azlUE7AWhP+emzDkjDBCh3DZHYcaScHPPofTl6HQvC5xxizZtVzvDGmyBKwQXrakuoU8CUq53Od5Om/mzq9i4Nt+nVJ00Uzk/Cb4zZCxHI6vAh3F2SRq/FGsDlbq40FabmDOhAbrbt7MPtSMdsv0LiHGIKr2qPtyaegYEZNk3ZzxgSpp5BR+Fcm7iENiA8AWRU6EqU4ACeqILGXanzFdgeN0FCnymsdwXj6By9EbtjBdul1KfWssX7nqxkRzA29ONpEsPN1J95RvJtuUWaFpGEP0qxxmIiAkqwLED/iICDzJJInVWbMmkctliFqshgaASBXADXEKz77Mp17ItarI9JF2NLOk53hM/NstgIIOcKQseQP9MRV7bct4iqRULab4H9z0BGa4LL8R+pKlurToiWSpqMCxlRpc9OZ4hKurdq7cReCkQPzF2HCe+3+yIlj1ePpPfdtc7tA+uiOIzsneZqB6B68YLJOKES+TPvPblYSdvRlU6BG6dNV6KMOHl4OsCz5L4VbP8k0icFf4I/erp6HcQzTM5bFbRq5utPYqULXlBCIz6snP2Fj77XU1pORaKZKVIJ93qBZuZL9TvqaVubfu5JpHMct/FXXh9zIUhcSlDTfhr1/9ADZFnz2+XWw6hTgMtoMQxFuFWI7nDBgysuFhAL/BY2eML78aM5uHnuWYk9cecKOmcypJZw/JpOh6aNHu2i0tk+DDt5/+nbgwfZmkaWnSoG0VUJ/UBF2N70CaZef5hnOTfJtfO9fb+FJD0cjOP6zig==
  template:
    metadata:
      name: alertmanager-discord
      namespace: monitoring
