---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: dev-app
spec:
  encryptedData:
    .dockerconfigjson: AgDij4+opc9FTmh7bJyJ3bPkOdWEg8Wa4OBJK/2WnbrmeO/YQZWNHGEYnt0waLmQgP84byzZbJSjHlbm9/hZel+aFQuPHaP7PCOQwDFXIaBUoE3apfV+a9YEVdQ0rDuUDLly5a4+GOCE52hh7dkV4FFgsrpO3Zjjlx1jMNtp0NU9b7yzWqX6tYvTMN/uONwQClb/FWGsjzDjskmmeyXEC6ipca1tismyYqjIer0kmP+wwrT1nmTOs3Z8l6YeXGVWFdgBhdrAtz6+/+oEpwKjQcOWdWzLMFI/b2LK9/P907pkv+1TA3a87EuVFm7fyBk/N+tmu1048ENQ/+1N7Vp14Ij5mtqB9Rhjy4eKLffe9dD7X/j8EKbYPUKi5ODA1a3qwIraIiWJSKhlEMrfKI4X9++8LfL+4BhM5qBvO/GVaJ3N1MZnMpwHg65XcF6M8FSdDzqfFeYP1m6zQRSsktOT6qCgJshtpH0UvRHU49rg2ra5dGTAXnXmh4SRz1ITvM5NCkVWp9uH5Uy7t0m2LDl5EL+w9LZTDSgsKZgbRq95pP7k1x2+faSahj9bkQSoX4hrERPK1NxmpPyGvyECV8K15TKtkjJzcuo4grw/Km+/vg9KXSlyt1Uokp56w1PY3icwHZM+UhVaS19vhOJzVmReTK67tT+XmhdzpcFR0xfo1M65T2V+/RUED/fkU7WRaSxTCgshZYfvciFLXmHZ7JW3yCtyCvbz+ezNkT5T5Y5qk1Qno9x4eHw/PPvc7lKfTSNeNysQiqnwlUq1r32G781XDr2fOihCDC+NrK8qTDcRU5UgddQgGBG3VNkjQmsLmbS3dCRMP/cRQ2iW5durfBqH+BgWvf/dUFmDidzcGzKvQiK/vJHyDQM1gjaKr8Sfhvt96LMLvyjbKxotdXb0tgDWk1KIH8YTVdKi6dxhbFU2csu7l7w=
  template:
    metadata:
      name: ghcr-pull
      namespace: dev-app
    type: kubernetes.io/dockerconfigjson
