---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: dev-app
spec:
  encryptedData:
    .dockerconfigjson: AgC5oEdGpga5cIuhzrsvTB/mE2jUsLbcapPexaXWRznspuf+ahKlK9D09fUeF51qaXjGEedMyApXsp25kVQQ//DEG9KGaN971iXdYYAXVUcqFbeA3IWZYYzC9d9fDk0XqgfYT3YjCliel0v4NwhQlaSZFUuU9vDa97X6YoyTMOHJdoZ53e4kQ8TlYyAIlOZ65SVzjWN7XnywcIH4igTxS8m6AcZMHJLkgPfZDhvvQmcxjjFUNDYZGPeehVUgdDo8vy1hD6ugXEN1Jra896JAln74QvcC7Fyq2qLhP9cqghXpnogj3b1evgBh4I6UYcDL8VEXzIjhXb0xJ0FZy6WWPsLyEm8jVLwcw4K9isHiQ/KwPFJcnmBzbUttakl6WvCfvG3qP/3dBu2BX4Zj/ioxJ36Nufa2ZjKq7J3vat42HZukO+yUXaCLhQCHaFopJ3c/+sFZzGg9zCq8Tszy6TCMNweaDRiUe4nsjfLueDT0HIraNsEJxJKIt5nQwAiOdbyYd0vPr9vPm3nIzlxuWEQrA1CKMmFYJCfy/b1AIHUdR+mVW9LdO+ZCTtzjCRb9W8JDh62qPmFq6LWrjc83xH2GeA11tioyF2+82Sd5DpcOpjGv8eO6rFxnJ3HGUuA1RDKvMbLQuK8zeUqlsowyClR4tJStu/sxYzMhBaugLtOir8bDcUC48cwPrmL9Cti4B9Z6SpdzYzFvxpIhpVreL1tDt6P6m5Uhh1aXd81dLr+cJ1Gxl8EPqktpWUHtXqTliGJjTMlo62gDZQXTIJfjtSyfFKnUSZ9XkcI+h7lRMagSoZTd6e5w0tsQqjuaIHge8iLYRqy/yIO05ny7xO4xLLcEqJZscSGfp43zr8nqMOK6kIBz/Bsz9QZ3HFECUgG5SV1ZppTQ0IQMkiFOhUoHw9kjSu/OyPllIKWfImac11hyBQQ290Y=
  template:
    metadata:
      name: ghcr-pull
      namespace: dev-app
    type: kubernetes.io/dockerconfigjson
