---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: app
spec:
  encryptedData:
    .dockerconfigjson: AgAlFe5kXXitOGKFislVcnbvYVvuzPlfXzx2C0MxZU8gaf0l0WD156KyuoqX4EIEQrv8co4Ycqsj4tRs6ofBt5t+FgPBp3zw0zyy3JQmnzghCw3t+vyMrYO8euNcYdBumorjLUYOdct+Qy/3yjwc/19ZDQS+R42twyuPzPkBo1emnLiIEy0ZBbPyrrl19nbW1Hsau4xdknk7FbDNKkSj6vyZrzDph66AsO8g4rFL/vrYC5VQkz8cw/XnDnVvOn17EURA95SH1Zvv6UqN+nhc8TbA9MmVMcmx0HMJ8eoaLH/IYxzTk3Neh7+Vumt8Y/jM47+BHg98RKwKow65sMHLbVljz1lGAwWFP3yBFFnvgBjqeZPufO7bpVl7uTJqRy405YSotK876RoRQbKNkUFHIyosSoT2GKv7SHuFmknvIQ5GPlbMgNlgdy2vtrhK/vnQVZ2sglo3TG9YLJQ7e/Xl62qcR57nZA1dI7xAW/UlEaZzSwDqgyJvn+TxYGOgOs49cA/RWoHphv31+Zeg/7uMhaglZ4RkEZRIynpHUufYz/dJFXm8NKzndzZD7/iTrFERTs45nxjkeEf+pljs2Dm//j/TdF8AIots2tONOT1bneEqZHMMDLpA1iDHqEleTZzcbSj2XWyzKmZpf9PNpeTZSQh4ida4FxR4CvMD/EkA3KhHR6B5efDV0EBuU8PkBvkAr1isA1udryRRYhx7XnK62CypfPcX6nipZ5nwuJRmq9AfcF/5bjwE7vy+e0HTi4OYlEKslnoX8uKKMjOkvZcrZb53l6zm3ivP1e5MVM2YiJL56fSBkEK1SwDehnsWAScyIq1YhsE0iKzSWZWzttxlaOD7s1ujxhb+G9t+5g8Ehcfhz4P+vHc0bqX7mB96+rDxqiCSD9Pq6H3Dk8yGqAOBXbX4NhLTRqq2UPGHBLs9p7xK8n0=
  template:
    metadata:
      name: ghcr-pull
      namespace: app
    type: kubernetes.io/dockerconfigjson
