---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: app
spec:
  encryptedData:
    .dockerconfigjson: AgDLJU6a0K7CFx0D5k6ur2/kxutnKnXF12yWH3pkgw5cPuzLvytUHBWSbV98vyGDWirNvDYH6w4lyi/WZsFvIjkqgKlJZzoNjnn88y0a0HwEOskBiQ2j77jBXJyLmNI7aulTYv4/tZYtOubHITbXWTSlyLDEuHOCRRmQIdpOi9YoAteuc7ADvW/alMxeUUK8WxzOK7HSiakwdLlRvVD/YAx9HCA7IiB179u4NZFlmI7s+BZ9qX//3o7VqVEZOwPw9uEROrjPSHH7yf1LaVS12VxxepaDdUd9VZyBQhT3QcJlMMF2Q2xnnX07thKnkczoo6LOfqHhfbVPKWBgNgVGk5oQRMzHZUvE69deKGSb2CTCqcMvqPgb37l4kOG0f02CoAv0mXggVowVS4i6HC7z6crUsHJmTzsvi3vTvliJv0eq00F5ikmRV+9Rut+myuN4iCSrtEhGKgSdXXLspGGSLr+DKoE4k3bx7iEeNPe1lBAbzLSJOEihW6nu/Gr7tqclGEVm1cbTGFGgZO7ixldu8lrxOt0st17Ju2EEQWt8Z1451k0SBqmg6IWUxmPvtU8zgGA1aUNW3CKvIlXNC4uFQTf8AM6t8YMZJBAr3r7tBJvUk4g4Qi155I4bJ5dSVvplyTqw6ox23R/Wg0SR4+jDChDeX/iOC6C+UbkxynDZmmMADYX/3AWhCkvCKV/Gwmv5tdzAa+27gXgyJeUB+NTSI63A/eDwKFgocRT/No3+cIdM00ePiGKzKBJp1yOBn8VbBeTWz+8ejhE5WUQP9+1QqbZa/utCqBVxiFuhXvJqrkPAbEqi/Ww8lfpxCvRmeQAwv/4LQfZq/chbNLlxoJ4Et10kLdg9klzJWOrbsnf8KsrBXbZNXe353PBBNruzf9Denqn0PK/jVqmmxiYppDeYiCjTHFeIo6xkPgePc4/P9HIJ4ao=
  template:
    metadata:
      name: ghcr-pull
      namespace: app
    type: kubernetes.io/dockerconfigjson
