---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBmwhaM5T1w05Jm1gCoVWIvhr4cC4Vrc/1G9GFtJuzFGYgs3TjI1goAicANjaq6UmzyTJoGi8F7qbSytyvjTx3HsrP5TKTxRRy5lBZvbOafr9Or8FjaiqRdX/HJZSnS565JVfKeuYwFUt3aBDKvRHXrsbF9L6mcQwP6/6n6kjS48/XgeHf7SLKyZh4LRJYd/toQG15eRERVbAPIHJauEvt0nnFYmNKkTMpvDRHIwEsea04VxgZHD2QNWjETxnkpDuXwKz1CUT0UK8SVxYefZc1Q+FYS3fV19Xvs0ou/2rSG4aG6aP5e4JE4uXq45qqvKCPpsfK84rXVn4oXpD0/OtXzd2Bg9yK/LmiWD8Cc0vpvge/JXAk/pr+AD8uSDDMq4cK+WKJBRAaKUt0sY23hmcqBNkFw/S93ixeCRdXpsiXAAv0fcugaHvevRT8piS0S9aTVL3lUpsGYGi0qsAttyAUVI/HU5MeZzjZ/WMHMhtNw5MKxy4UpgCHLaJXERO6jc9bYZy9l/qNa/ldvA/nWMRRgHEzB1RCshTfh9ygvPtOQ3coCZTSyzCIb7MY/RCLrqT/5/wWY2sS+h/nWiStOZpOKMfChaD2EoMPJcdh/cl1pOtfqg9RPX1vcKL2T4zqDewl6UX1PFPFmFpbECkOFMAQMRjlG7QwLjgqnV2nFemzd3KGppYDYL97/QW3sGsc1tMLqfNAhk67jPWS2BK0z98ieBmMaqW3F9Bo=
    admin-user: AgAqe3dQt0Yvj1TZ8ykYFjh+KV7tu7TWbbb8MG3EFKimkt6GJNsgvfUL44zbFRdt9osoP+IkXVdVtT+m6FIQTnYpc9Mflr5Rtd2556QZjA+rin+DB1SwsGyof9KiDO8br8WTp2iPM+CKQH1vl8EnxPngpAtwHh1CyPcyWwoQKtF5i7sgybzrpzBU4GlzQyrqT+krXbDRPqcNwa2U6gE7xMR61CJ7M9XBBuRa6iAdMO30X2agpSHuaS8E7rDQ65FQXPaKfFG3lIdM03Sg3yfQ+NjKk9RxC0Hp5hwuP/R1zrMxfgvTCKwSpgcUi8ubR7F4v47g1tAonhabmGj5Vftr1Dd8CpMOlnNmq8FmGmC7PKNaFi5axEgMXzkQB92eBTl+VIB5QrMGXhMMgpM8sSgyGLn1aTzUIB79AQp03JxPkK6W68If8QvhQ010+0DzN0udbKMoowW/EpM/RcKPK+Ush9FCRx8PgLIK9dFlKzvvp9i9Zfrm6xm1wBfmd+3c149FkwwD2+qTQs1XofU+rFUjoyOk/kJGS/Tau/N9D49oqFyHSQlQjDG73Zbz8hDFlHtXfl4KPUz3Qy8wqKRqvfmrg8woNzJgEfgk6wuFBhg3zpWyKHl0PCLXiDUs06oCEyH/HMPpQJjKLygumZ4l6sxkUSRKZvaXnwd1GVPFEzjWk9V8e1BumlR+HJtvVRvhh9jsvGXyjLbJYg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
