---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-readonly
  namespace: db
spec:
  encryptedData:
    RO_PASSWORD: AgAAjAKpqm9SmnpLsqBqCVej7QzJluADZFjq/gdhmI0G8YYP4EdCOVhEgbHYGYfQG8XZyrkuvyAi/V2bzxQN5hOhssZO2NHdb8fnxGewXACjEp1C/zgJAcegFEAUDmLQglCmyVvVJQlqMQArujdHxjcN9dzQbRrYj9ErcUpGAo4bvLxF7wORKJQn2/LMuEf27iXrqdqC9vCavRqbbDFeEN76x2dhvDJjKfVCxaf5wa02ua5Bmq1oUeDwoI4QWBRdN7OC7Hp4BMQVXejRMM5VrtOEbnkEQuTjh8Tk9/2NWgs2N1YpdJ1jBeh+u3Axa6q4LU+7m/yHjcK2isJX1HmdJ/vEAqEIIyYHbrr9G6rmnYhWEupI90DISeSdaJWu90B+L6HWDw6Se2CPMabSNFZ9KgVpD2CG0oZSbRvEJdC/6EP6jY9shultwC4jzsxr6GImN846ksNZOrRnMhj9SrP59zSaASPcD8rLnp0Dolg+SKN6ZOXUFqr4JdD0IoBSc2Jvl/LNqJ4iCwqFrZhGyDJCJg1JDi0G1OjdWxSUKV5I3hePhXulKyrhph7g3eKwLtguNLBSJEjOfh4/qDGEQcCMu9gqsHap4j0gOyXMI2WZLjvudWRCb0TJRDdKZY40sE6EIm3M4c8B7B138cF1UPMRK4EHHbinIvVlpTX5A7252SyijznDsebWfiSpFDlX/kibLljQ5MkUqPgrcD7nBzGzR3xg73S+qHH8u1A=
  template:
    metadata:
      name: postgres-readonly
      namespace: db
