---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-preview-secrets
  namespace: preview
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgB6ueHgsXAWgbxIJtph3+lCkOfAkaezjYPS5izx3jq2rSW3Xhks94/FqrW/SOYEk4l61kWwtemJuAgq07Y7f7muBELeBo8XqrYy8NlfeAEB2isxtKV1jvMorVFMfJ4LZJu0gmzCtT8KacYCOJSfw8TEwj9qX0F04T1HySV6eejJfdjNmS8oGxtekybSemgnKawAW7VPtb5NLuv8xFTh6iC06uCYCcHM6zxEB55ESOgChfZfVBiWw9fLLMiqchhMYjFlAsEURAkxwky/pg5jy/yHN6Yae9obJCJ8WJMwW9GDh5p1u4zJoVcl6NVNug4hT9mWD2seo8LCp1YXH0MbqExq0iqqbM9HiZrXreGSyoQtXKTVWxqlaLJ2xhrMmrkwIjaRAP1OT1JynTYVYPEcJgJ5kZLJHuLWYwWDUTs5MTAZkngSGSAG95zTsFkIA8FyKYmnKd4xSoGqEnYkV65g9sDXGXthNyvu6FiRm2xa/3RBJkQzNIK+sm+7cMkSFIQp68E3cZBAjKxm69RJ9KykEYGtTPZlcptZ57HV6lQ0aLd1wTg4zejEm71BoaeJXdZrYASzYhP4XOtCd58oyFHaiEKb7qwz6BaTtiPhNsNjo19dmu9mwa5tHWl5fyeJAHag2B37QAFD5SLK4ct/RHWOCO6vb9Z/yL/HXur9tWaqNBf/3ObK6OdCWqgtedJOmlFk6uEH+zl87sf8L1MBq7ixUADQUXPCHPkNw6s=
    POSTGRES_USER: AgBYfTQAaF7x2H8VD1huYMlg/yYzeh5Div22BqzJyXfsPHC3el6S5F/bAPUeku4XngokRD50es+scS7Kiwv8Fh2+aKI1I6lLMGWrR2cFZaKhHNPTBMw3xbO7DZmYrJSr25X8TFfNYSN266tVCADDddddcqkkE7Uj4kbc1Zs0bm01DRgyyPWLnTdw/v8HPYDpGBEGVinTE92W9lxFX9XgsWf08lQPLerZkXqms4zOqzazkQ8bpdxWs33o7Ztk3LIsK53jMLNtym4M8usUXeijF1gab8M1/ZOHZKTpDdstQmN/apO4Um21mWoqDV1peAZGZJDrwkpEfcdKx1KLpaPeIzGJvqc4nsDeieKgpvGNUQbnUw0/aEbmdCrQqKy/0gD9haA0l7ata3j5dv6d2tL2RrkbAQVA2jjFtwwT7lAVdo4HCerbAwnZoOQJkdf5HjqEp3VMQUFIr6i8EzKBBPxSFAT8dyrwETxdt03L8eNw20LvhweRVT9lHIAozQTpUIYdqXzBEUkbednDEUEraYHQp309y/KavJGzlxv77oNF5brk1NxF70VqgDSTWJiqL+3K1F9W0HaBGiCn5bcSaxJmpmorHWMF/KTAq1IpnLLRsaVEPxBodsAUXKW7kGp1Vn/BeLOTD7hYAQhKo4Kwu9yQUDMsoGYRcTpzFhoNOfDMN6N3f17S1v1AD+++6mv82Ozl0O0AAkbOjRw=
  template:
    metadata:
      name: postgres-preview-secrets
      namespace: preview
