---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull
  namespace: preview
spec:
  encryptedData:
    .dockerconfigjson: AgCMUV3xD71/lrZPpXu/+HYIEgk7JzkcwRU2KHPb1emXvN4q5FBEZrFivbjwiBGwImZhtyo4OtIBDLlNZ4LCu2cgmaaDASQ8ml6h+vphGkDKj2K1gOrPlHjsZWWyK3k9GTN5Hu6r8OGPQPyLXnMxLfoSYE/VY4aihiR1eSKe6DDRlDHpzX7DKKa5q3Dq7pRKoCgNNY6jMCvoEOsenDxc669jqu5Ib0miaULsuE5p6W0xWGD26XbBC7YYrvqJKFnFfzbf5S+pXVkYNyVvjHUdgkIyFHpnPfjFeQnylvg4GrGFYbUsZTdAnJhalmzuD4fv6VV7gkeq11sRBQXNdTQvXUzcnvrhYFFqxKZOSxofXxNjQQyYFy42QfiFPuNbb8DHcfPpTc0eEzngoQnky3rttXHE4Gtid3zEL7WDkXbjPDdZFWWLLJF60Bw4+mzorceTciQDKultCGQpJ9QCSYASDswov+xWSvAQ+8YowsEtxUYCh9iC7NdrEZOXlY9z70XEaFe7SJxwUxfkvCXx1T4IUaeZr+L6O+5KmTao1Nu+w1iEdMjPo8hhZso+l2+qdNAf+i6Tfa5i9WIQ6ptfzKrWsJ3zUFpQ0TZMVbUBa5i8ugXe/nLY56E0eCrZXyDx6pIl5HQzPww3JHP+nKsWCb7Y/bbK9ff2D7Gg435X/iTomoGNT+jNMpY+zjnd4PUgsd+5qLX/VzX1BrSQyRFrL0Ay4GvxqpF7r8NOt9OfQC2o5zp/bxRstBLZwHe/oqdNs0yYUl2qKN/5esMkEMp9i8X69Ye60sNM5AJOWaWvp+o6RWorMdEW+RZH2aJGrm5Yzc2tAvPpH88gIoQXytFDdjaGcekIpnPFlkGg+gz1A137r3tgSQTknVMTcHRSoMQ9Z7Bfi2LyPihmcMxCu31QiusbKmVtY7ww84N1u67RXlXNNGlIiYM=
  template:
    metadata:
      name: ghcr-pull
      namespace: preview
    type: kubernetes.io/dockerconfigjson
