---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: preview-github-token
  namespace: argocd
spec:
  encryptedData:
    token: AgA7dadVOL68yo36yYG9TvQC50aSvgBpDKbhvluL5eogJLUSU9Pg5se8XJnPAhHYN+EYkmqbnSFRKDikBoAH4gPyI3nZ9G37VyuqzTPgm7/1U3AXBsRY85GP2xycdbXcEpewUD/iA1bb46dc2iODcuAkwU7nXW1/5DNbmflRhM4oqeCefH0kw1N7CpsbZPjkYt+QD6TNfW+xJmWzfCmCFzFl7DW92KRbSr1TpfV/ZIUb84slrsZ4OwFp67S5l90Orp9PB/UwHWiHetfFBEV5hcCWQq3l1h2pcO1qYUh4A4RYnCZrXglkoLy0UvfnPBDOFeBXId064AuFwQ7e/K4fEpQkzNXPbjRFZQ481yDTm2XFjrRbLdwczBfLgkgepXWlQ+ZBzXj33hjxJUrjHitVta54DGkfsS5puRZ4iTbLLLsPJ5+ZqHNiVf32D1fGZ+ogKceEz3Y2zbGI79NoXblx2Q//QMPeJ7fT6G1FBywLMvsGovKMOhm76isJwqKqzQIQFLNbULd5u4UI0jRDnkzVSJlgtvu95q63QgG9mX62v1uWUVMNvk/CRxF6RB/4B+kA9GMDf7EaVC1gSIxHMUNqPBAIlniuRknq9lW7015ZQjTFrSHJRsF4o8XUw0REtmOYeFZhrYWq5JGlQsURLh1vOPsO0aUDLSgAdEn7AEduh8BTDO/TY70dk4Et5KIO40E52OW6Mm1vIqZPVfvix1V1umBO9rDR/SzHW5bcVLBrB77kSa7sJU0l82Ulq3F7/wNXX++KlxfpKJvEiI49BbxH5NCAChttHluZKoADSOWYmLZseycxrxjHMq0prtUg+Po=
  template:
    metadata:
      name: preview-github-token
      namespace: argocd
